backend:
  name: github
  repo: cdubos-fr/pexiora-tt
  branch: main
  use_graphql: true
  auth_endpoint: auth
  commit_messages:
    create: "feat: ajout d'un nouvelle article {{collection}} “{{slug}}”"
    update: "feat: mise à jour de {{collection}} “{{slug}}”"
    delete: "feat: suppression de {{collection}} “{{slug}}”"
    uploadMedia: "feat: ajout de média “{{path}}”"
    deleteMedia: "feat: suppression de média “{{path}}”"
    openAuthoring: "{{message}}"

# Configuration des médias
media_folder: "source/static/images/uploads"
public_folder: "/images/uploads"

# Localisation
locale: "fr"

# Configuration des collections
collections:
  # Actualités
  - name: "actualites"
    label: "Actualités"
    folder: "source/content/actualites"
    create: true
    slug: "{{year}}{{month}}{{day}}-{{slug}}"
    filter:
      field: template
      value: page.html
    fields:
      - { label: "Titre", name: "title", widget: "string", required: true }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Date", name: "date", widget: "datetime", required: true }
      - {
          label: "Image",
          name: "extra.image",
          widget: "image",
          required: false,
        }
      - {
          label: "Description de l'image",
          name: "extra.image_description",
          widget: "string",
          required: false,
        }
      - { label: "Contenu", name: "body", widget: "markdown", required: true }

  # Pages modifiables
  - name: "pages"
    label: "Pages"
    files:
      - label: "Adhésions"
        name: "adhesions"
        file: "source/content/le-club/adhesions.md"
        fields:
          - { label: "Titre", name: "title", widget: "string", required: true }
          - { label: "Description", name: "description", widget: "text" }
          - {
              label: "Contenu",
              name: "body",
              widget: "markdown",
              required: true,
            }
      - label: "Horaires"
        name: "horaires"
        file: "source/content/le-club/horaires.md"
        fields:
          - { label: "Titre", name: "title", widget: "string", required: true }
          - { label: "Description", name: "description", widget: "text" }
          - {
              label: "Contenu",
              name: "body",
              widget: "markdown",
              required: true,
            }
      - label: "Staff"
        name: "staff"
        file: "source/content/le-club/staff.md"
        fields:
          - { label: "Titre", name: "title", widget: "string", required: true }
          - { label: "Description", name: "description", widget: "text" }
          - {
              label: "Contenu",
              name: "body",
              widget: "markdown",
              required: true,
            }
      - label: "Equipes"
        name: "equipes"
        file: "source/content/le-club/equipes.md"
        fields:
          - { label: "Titre", name: "title", widget: "string", required: true }
          - { label: "Description", name: "description", widget: "text" }
          - {
              label: "Contenu",
              name: "body",
              widget: "markdown",
              required: true,
            }
      - label: "Contact"
        name: "contact"
        file: "source/content/contact.md"
        fields:
          - { label: "Titre", name: "title", widget: "string", required: true }
          - { label: "Description", name: "description", widget: "text" }
          - {
              label: "Contenu",
              name: "body",
              widget: "markdown",
              required: true,
            }
      - label: "Mentions légales"
        name: "mentions-legales"
        file: "source/content/mentions-legales.md"
        fields:
          - { label: "Titre", name: "title", widget: "string", required: true }
          - { label: "Description", name: "description", widget: "text" }
          - {
              label: "Contenu",
              name: "body",
              widget: "markdown",
              required: true,
            }

  # Sponsors
  - name: "sponsors"
    label: "Sponsors"
    folder: "source/content/sponsors"
    create: true
    slug: "{{slug}}"
    filter:
      field: template
      value: page.html
    fields:
      - { label: "Nom", name: "title", widget: "string", required: true }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Logo", name: "extra.image", widget: "image", required: false }
      - {
          label: "Site web",
          name: "extra.site",
          widget: "string",
          required: false,
        }
      - { label: "Contenu", name: "body", widget: "markdown", required: true }
