base_url = "/"
title = "Pexiora TT"
description = "Site web vitrine du club de tennis de table de Pexiora."
author = "Dev'Oc"

# Configuration du th√®me et de la langue
default_language = "fr"
generate_feeds = true
feed_filenames = ["feed.xml"]
compile_sass = true
minify_html = true
build_search_index = true

# Configuration Markdown
[markdown]
highlight_code = true
highlight_theme = "base16-ocean-light"
render_emoji = true
external_links_target_blank = true
external_links_no_follow = true
external_links_no_referrer = true
smart_punctuation = true

# Configuration des liens
[link_checker]
internal_level = "error"
external_level = "warn"

# Taxonomies
taxonomies = [
  { name = "tags", feed = true },
  { name = "categories", feed = true },
]
